# Generated by Django 5.1.7 on 2025-04-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
